[package]
name = "godot-codex-mcp-server"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
godot-codex-semantic-model = { path = "../semantic-model" }
rmcp.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true

[lints]
workspace = true
